apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-host
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: web-host
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-host
    spec:
      containers:
      - name: web-host
        image: %IMAGE-NAME%:%IMAGE-TAG%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: web-host
  labels:
    app: web-host-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: web-host
---
apiVersion: v1
kind: Pod
metadata:
  name: db-host
  labels:
    app: db-host
spec:
  containers:
  - name: db-count
    image: redis
    ports:
    - containerPort: 6379 
---
apiVersion: v1
kind: Service
metadata:
  name: db-host
  labels:
    app: db-host-svc
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: db-host
